// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Van Bien",
            "email": "vanbien2402@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/heath_check": {
            "get": {
                "description": "Heath Check",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Heath Check",
                "responses": {
                    "200": {
                        "description": "connected!",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/prime_number": {
            "get": {
                "description": "Get input number and return the highest prime number",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "FindHighestPrimeNumber",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "positive number",
                        "name": "inputNumber",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The highest prime number lower than 10 is 7",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Please enter a positive integer.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "There is not any prime number lower than 2",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "52.200.150.234:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "My-application",
	Description:      "This is application which takes input number and return to user the highest prime number",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
